//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.0
//     from Assets/Gameplay Input Actions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Gameplay Input Actions.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @GameplayInputActions: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @GameplayInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Gameplay Input Actions"",
    ""maps"": [
        {
            ""name"": ""Wandering"",
            ""id"": ""a0c9b419-9821-4aa4-bf50-51b46401fa6d"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""5685cfeb-3f72-4748-aa91-9ddc6d2b0212"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Enter building"",
                    ""type"": ""Button"",
                    ""id"": ""eb6b2519-ee22-4255-b1e6-7bb5eb3f4e1b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""e61cbd14-80ff-4269-b099-3459b0e9cb46"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""20babcbe-81d9-4e05-8ba1-68465e10c645"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""2eb6f877-bfb2-4cc0-ba1b-e55974ee14a3"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""4aa3bd1e-8976-4e16-a77c-099358d26f50"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""267adfba-2cc5-48ca-b744-2d4e8d958f66"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""56688b17-893f-48eb-a236-9b68c537eebe"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Enter building"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""In Building"",
            ""id"": ""289300d1-5069-4047-83de-71436a7aaedc"",
            ""actions"": [
                {
                    ""name"": ""Exit Building"",
                    ""type"": ""Button"",
                    ""id"": ""745750f4-1226-4635-a001-b5518f542c7c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e7516321-074c-4878-965a-323f2489c611"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Exit Building"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Wandering
        m_Wandering = asset.FindActionMap("Wandering", throwIfNotFound: true);
        m_Wandering_Movement = m_Wandering.FindAction("Movement", throwIfNotFound: true);
        m_Wandering_Enterbuilding = m_Wandering.FindAction("Enter building", throwIfNotFound: true);
        // In Building
        m_InBuilding = asset.FindActionMap("In Building", throwIfNotFound: true);
        m_InBuilding_ExitBuilding = m_InBuilding.FindAction("Exit Building", throwIfNotFound: true);
    }

    ~@GameplayInputActions()
    {
        UnityEngine.Debug.Assert(!m_Wandering.enabled, "This will cause a leak and performance issues, GameplayInputActions.Wandering.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_InBuilding.enabled, "This will cause a leak and performance issues, GameplayInputActions.InBuilding.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Wandering
    private readonly InputActionMap m_Wandering;
    private List<IWanderingActions> m_WanderingActionsCallbackInterfaces = new List<IWanderingActions>();
    private readonly InputAction m_Wandering_Movement;
    private readonly InputAction m_Wandering_Enterbuilding;
    /// <summary>
    /// Provides access to input actions defined in input action map "Wandering".
    /// </summary>
    public struct WanderingActions
    {
        private @GameplayInputActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public WanderingActions(@GameplayInputActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Wandering/Movement".
        /// </summary>
        public InputAction @Movement => m_Wrapper.m_Wandering_Movement;
        /// <summary>
        /// Provides access to the underlying input action "Wandering/Enterbuilding".
        /// </summary>
        public InputAction @Enterbuilding => m_Wrapper.m_Wandering_Enterbuilding;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Wandering; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="WanderingActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(WanderingActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="WanderingActions" />
        public void AddCallbacks(IWanderingActions instance)
        {
            if (instance == null || m_Wrapper.m_WanderingActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_WanderingActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @Enterbuilding.started += instance.OnEnterbuilding;
            @Enterbuilding.performed += instance.OnEnterbuilding;
            @Enterbuilding.canceled += instance.OnEnterbuilding;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="WanderingActions" />
        private void UnregisterCallbacks(IWanderingActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @Enterbuilding.started -= instance.OnEnterbuilding;
            @Enterbuilding.performed -= instance.OnEnterbuilding;
            @Enterbuilding.canceled -= instance.OnEnterbuilding;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="WanderingActions.UnregisterCallbacks(IWanderingActions)" />.
        /// </summary>
        /// <seealso cref="WanderingActions.UnregisterCallbacks(IWanderingActions)" />
        public void RemoveCallbacks(IWanderingActions instance)
        {
            if (m_Wrapper.m_WanderingActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="WanderingActions.AddCallbacks(IWanderingActions)" />
        /// <seealso cref="WanderingActions.RemoveCallbacks(IWanderingActions)" />
        /// <seealso cref="WanderingActions.UnregisterCallbacks(IWanderingActions)" />
        public void SetCallbacks(IWanderingActions instance)
        {
            foreach (var item in m_Wrapper.m_WanderingActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_WanderingActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="WanderingActions" /> instance referencing this action map.
    /// </summary>
    public WanderingActions @Wandering => new WanderingActions(this);

    // In Building
    private readonly InputActionMap m_InBuilding;
    private List<IInBuildingActions> m_InBuildingActionsCallbackInterfaces = new List<IInBuildingActions>();
    private readonly InputAction m_InBuilding_ExitBuilding;
    /// <summary>
    /// Provides access to input actions defined in input action map "In Building".
    /// </summary>
    public struct InBuildingActions
    {
        private @GameplayInputActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public InBuildingActions(@GameplayInputActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "InBuilding/ExitBuilding".
        /// </summary>
        public InputAction @ExitBuilding => m_Wrapper.m_InBuilding_ExitBuilding;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_InBuilding; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="InBuildingActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(InBuildingActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="InBuildingActions" />
        public void AddCallbacks(IInBuildingActions instance)
        {
            if (instance == null || m_Wrapper.m_InBuildingActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_InBuildingActionsCallbackInterfaces.Add(instance);
            @ExitBuilding.started += instance.OnExitBuilding;
            @ExitBuilding.performed += instance.OnExitBuilding;
            @ExitBuilding.canceled += instance.OnExitBuilding;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="InBuildingActions" />
        private void UnregisterCallbacks(IInBuildingActions instance)
        {
            @ExitBuilding.started -= instance.OnExitBuilding;
            @ExitBuilding.performed -= instance.OnExitBuilding;
            @ExitBuilding.canceled -= instance.OnExitBuilding;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="InBuildingActions.UnregisterCallbacks(IInBuildingActions)" />.
        /// </summary>
        /// <seealso cref="InBuildingActions.UnregisterCallbacks(IInBuildingActions)" />
        public void RemoveCallbacks(IInBuildingActions instance)
        {
            if (m_Wrapper.m_InBuildingActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="InBuildingActions.AddCallbacks(IInBuildingActions)" />
        /// <seealso cref="InBuildingActions.RemoveCallbacks(IInBuildingActions)" />
        /// <seealso cref="InBuildingActions.UnregisterCallbacks(IInBuildingActions)" />
        public void SetCallbacks(IInBuildingActions instance)
        {
            foreach (var item in m_Wrapper.m_InBuildingActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_InBuildingActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="InBuildingActions" /> instance referencing this action map.
    /// </summary>
    public InBuildingActions @InBuilding => new InBuildingActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Wandering" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="WanderingActions.AddCallbacks(IWanderingActions)" />
    /// <seealso cref="WanderingActions.RemoveCallbacks(IWanderingActions)" />
    public interface IWanderingActions
    {
        /// <summary>
        /// Method invoked when associated input action "Movement" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMovement(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Enter building" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnEnterbuilding(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "In Building" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="InBuildingActions.AddCallbacks(IInBuildingActions)" />
    /// <seealso cref="InBuildingActions.RemoveCallbacks(IInBuildingActions)" />
    public interface IInBuildingActions
    {
        /// <summary>
        /// Method invoked when associated input action "Exit Building" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnExitBuilding(InputAction.CallbackContext context);
    }
}
